<html>
<head>
    <title>Manage Favorites</title>
</head>
<body>
<p>Wyszukaj ulubione wydarzenie po ID</p>
<form action="oneFavorite" method="get">
    <label for="userId">User Id:</label>
    <input type="text" id="userId" name="userId"><br><br>
    <label for="favoriteId">Id:</label>
    <input type="text" id="favoriteId" name="favoriteId"><br><br>
    <input type="submit" value="Submit">
</form>
</body>
</html>